apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: root-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: root-certificate
  namespace: cert-manager
spec:
  secretName: root-secret
  duration: 9125h
  renewBefore: 360h
  commonName: root-ca.test
  isCA: true
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
    rotationPolicy: Always
  issuerRef:
    name: root-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: gateway-api-issuer
spec:
  ca:
    secretName: root-secret